### save editor
POST http://localhost:8080/editoras
Content-Type: application/json

< ./editor.json

### save category
POST http://localhost:8080/categorias
Content-Type: application/json

< ./category.json

### save book1
POST http://localhost:8080/books
Content-Type: application/json

< ./book1.json

### save all books
GET http://localhost:8080/books
Content-Type: application/json

### save all editor
GET http://localhost:8080/editoras
Content-Type: application/json